version: '3'

services:
  php:
    container_name: rbk_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./:/var/www
    depends_on:
      - postgres

  nginx:
    container_name: rbk_nginx
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/nginx_host.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    ports:
      - '80:80'
    depends_on:
      - php

  postgres:
    container_name: rbk_postgres
    image: postgres:15.3
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: rbk_user
      POSTGRES_DB: rbk_db
      POSTGRES_PASSWORD: rbk_password

volumes:
  pgdata:
